package xyz.w4ve.beaconator.io;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.NbtAccounter;
import net.minecraft.nbt.NbtIo;
import net.minecraft.nbt.Tag;
import xyz.w4ve.beaconator.model.BitPacking;
import xyz.w4ve.beaconator.model.BlockSink;
import xyz.w4ve.beaconator.model.GridDetector;
import xyz.w4ve.beaconator.model.GridNode;
import xyz.w4ve.beaconator.model.PerimeterPlan;

/**
 * Reads and writes Litematica schematics, so a plan can come from, or go to, the rest of the
 * build team.
 *
 * <p>The format is a gzipped NBT compound holding one region per schematic. Block states are a
 * palette plus a tightly packed bit array where values are allowed to straddle two longs, which
 * is the older packing style, not vanilla's {@code PackedBitStorage}.
 */
public final class LitematicIO {
	/** Data version of Minecraft 1.21, written so other tools know what they are reading. */
	private static final int DATA_VERSION = 3953;
	private static final int SCHEMATIC_VERSION = 6;
	private static final String AIR = "minecraft:air";
	/** Our own metadata key holding the world corner the schematic was cut from. */
	private static final String ORIGIN_TAG = "BeaconatorOrigin";

	private LitematicIO() {
	}

	// ------------------------------------------------------------------- write

	/** Writes the plan as a schematic. Air fills everything the plan does not ask for. */
	public static void write(Path path, PerimeterPlan plan, String author) throws IOException {
		int[] bounds = plan.schematicBounds();

		if (bounds == null) {
			throw new IOException("Nothing to export, every node was removed");
		}

		int sizeX = bounds[3] - bounds[0] + 1;
		int sizeY = bounds[4] - bounds[1] + 1;
		int sizeZ = bounds[5] - bounds[2] + 1;
		long volume = (long) sizeX * sizeY * sizeZ;

		if (volume > Integer.MAX_VALUE) {
			throw new IOException("Schematic would be " + volume + " blocks, too big to write");
		}

		List<String> palette = new ArrayList<>();
		Map<String, Integer> paletteIndex = new HashMap<>();
		palette.add(AIR);
		paletteIndex.put(AIR, 0);

		int[] indices = new int[(int) volume];
		int[] total = {0};

		BlockSink sink = (x, y, z, id) -> {
			int index = paletteIndex.computeIfAbsent(id, key -> {
				palette.add(key);
				return palette.size() - 1;
			});

			int local = ((y - bounds[1]) * sizeZ + (z - bounds[2])) * sizeX + (x - bounds[0]);
			indices[local] = index;
			total[0]++;
		};

		for (GridNode node : plan.nodes()) {
			plan.forEachBlock(node, sink);
		}

		int bits = BitPacking.bitsFor(palette.size());
		long[] packed = BitPacking.pack(indices, bits);

		CompoundTag region = new CompoundTag();
		region.put("Position", vec3(0, 0, 0));
		region.put("Size", vec3(sizeX, sizeY, sizeZ));
		region.put("BlockStatePalette", paletteTag(palette));
		region.putLongArray("BlockStates", packed);
		region.put("TileEntities", new ListTag());
		region.put("Entities", new ListTag());
		region.put("PendingBlockTicks", new ListTag());
		region.put("PendingFluidTicks", new ListTag());

		CompoundTag regions = new CompoundTag();
		regions.put(plan.name(), region);

		long now = System.currentTimeMillis();
		CompoundTag metadata = new CompoundTag();
		metadata.put("EnclosingSize", vec3(sizeX, sizeY, sizeZ));
		// A schematic has no world coordinates of its own, so the corner it was cut from is kept
		// here. Our own files come back exactly where they belong; other people's files do not
		// carry this and get placed by hand.
		metadata.put(ORIGIN_TAG, vec3(bounds[0], bounds[1], bounds[2]));
		metadata.putString("Author", author == null ? "" : author);
		metadata.putString("Description", "Beacon perimeter generated by Beaconator");
		metadata.putString("Name", plan.name());
		metadata.putInt("RegionCount", 1);
		metadata.putLong("TimeCreated", now);
		metadata.putLong("TimeModified", now);
		metadata.putInt("TotalBlocks", total[0]);
		metadata.putInt("TotalVolume", (int) volume);

		CompoundTag root = new CompoundTag();
		root.putInt("Version", SCHEMATIC_VERSION);
		root.putInt("SubVersion", 1);
		root.putInt("MinecraftDataVersion", DATA_VERSION);
		root.put("Metadata", metadata);
		root.put("Regions", regions);

		Files.createDirectories(path.getParent());
		NbtIo.writeCompressed(root, path);
	}

	// -------------------------------------------------------------------- read

	/**
	 * Rebuilds a plan from a schematic that holds beacons.
	 *
	 * @param fallbackOrigin world corner to drop the schematic at when it does not carry one,
	 *                       which is the case for every file this mod did not write. Null keeps
	 *                       the schematic's own coordinates, which start at zero
	 */
	public static PerimeterPlan read(Path path, String name, String dimension, int[] fallbackOrigin)
			throws IOException {
		CompoundTag root = NbtIo.readCompressed(path, NbtAccounter.unlimitedHeap());
		CompoundTag regions = root.getCompound("Regions");

		if (regions.isEmpty()) {
			throw new IOException("No regions in " + path.getFileName());
		}

		int[] origin = readOrigin(root.getCompound("Metadata"), fallbackOrigin);

		List<int[]> beacons = new ArrayList<>();
		Map<String, Integer> blockCounts = new HashMap<>();
		Map<Long, String> byPosition = new HashMap<>();

		for (String regionName : regions.getAllKeys()) {
			readRegion(regions.getCompound(regionName), beacons, blockCounts, byPosition);
		}

		if (beacons.isEmpty()) {
			throw new IOException("No beacons in " + path.getFileName() + ", this is not a beacon perimeter");
		}

		String pyramidBlock = mostCommon(blockCounts);
		int level = detectLevel(beacons, byPosition, pyramidBlock);
		List<int[]> markers = new ArrayList<>();
		String markerBlock = null;

		for (int[] beacon : beacons) {
			String above = byPosition.get(key(beacon[0], beacon[1] + 1, beacon[2]));

			if (above != null && !above.equals(PerimeterPlan.BEACON_BLOCK)) {
				markers.add(new int[] {beacon[0], beacon[1] + 1, beacon[2]});
				markerBlock = above;
			}
		}

		GridDetector.Input input = new GridDetector.Input(beacons, markers, pyramidBlock, markerBlock, level);
		PerimeterPlan plan = GridDetector.detect(name, dimension, input);

		if (origin != null) {
			plan.setCenter(plan.centerX() + origin[0], plan.beaconY() + origin[1], plan.centerZ() + origin[2]);
		}

		return plan;
	}

	/** True when the file carries a world corner, meaning it can be reloaded exactly in place. */
	public static boolean hasOrigin(Path path) throws IOException {
		CompoundTag root = NbtIo.readCompressed(path, NbtAccounter.unlimitedHeap());
		return root.getCompound("Metadata").contains(ORIGIN_TAG);
	}

	private static int[] readOrigin(CompoundTag metadata, int[] fallback) {
		if (metadata.contains(ORIGIN_TAG)) {
			CompoundTag origin = metadata.getCompound(ORIGIN_TAG);
			return new int[] {origin.getInt("x"), origin.getInt("y"), origin.getInt("z")};
		}

		return fallback;
	}

	private static void readRegion(CompoundTag region, List<int[]> beacons,
			Map<String, Integer> blockCounts, Map<Long, String> byPosition) throws IOException {
		CompoundTag position = region.getCompound("Position");
		CompoundTag size = region.getCompound("Size");
		int originX = position.getInt("x");
		int originY = position.getInt("y");
		int originZ = position.getInt("z");
		int sizeX = size.getInt("x");
		int sizeY = size.getInt("y");
		int sizeZ = size.getInt("z");

		// Sizes may be negative, which means the region grows the other way from its origin.
		int stepX = sizeX < 0 ? -1 : 1;
		int stepY = sizeY < 0 ? -1 : 1;
		int stepZ = sizeZ < 0 ? -1 : 1;
		int spanX = Math.abs(sizeX);
		int spanY = Math.abs(sizeY);
		int spanZ = Math.abs(sizeZ);

		ListTag paletteTag = region.getList("BlockStatePalette", Tag.TAG_COMPOUND);
		List<String> palette = new ArrayList<>(paletteTag.size());

		for (int index = 0; index < paletteTag.size(); index++) {
			palette.add(paletteTag.getCompound(index).getString("Name"));
		}

		long[] states = region.getLongArray("BlockStates");

		if (palette.isEmpty() || states.length == 0) {
			return;
		}

		int bits = BitPacking.bitsFor(palette.size());
		long volume = (long) spanX * spanY * spanZ;

		for (int local = 0; local < volume; local++) {
			int value = BitPacking.read(states, local, bits);

			if (value < 0 || value >= palette.size()) {
				throw new IOException("Corrupt block states at index " + local);
			}

			String block = palette.get(value);

			if (AIR.equals(block) || block.endsWith(":air") || block.isEmpty()) {
				continue;
			}

			int y = local / (spanX * spanZ);
			int rest = local % (spanX * spanZ);
			int z = rest / spanX;
			int x = rest % spanX;

			int worldX = originX + x * stepX;
			int worldY = originY + y * stepY;
			int worldZ = originZ + z * stepZ;

			byPosition.put(key(worldX, worldY, worldZ), block);
			blockCounts.merge(block, 1, Integer::sum);

			if (PerimeterPlan.BEACON_BLOCK.equals(block)) {
				beacons.add(new int[] {worldX, worldY, worldZ});
			}
		}
	}

	/** Counts how many pyramid layers sit under a beacon. */
	private static int detectLevel(List<int[]> beacons, Map<Long, String> byPosition, String pyramidBlock) {
		if (pyramidBlock == null) {
			return 4;
		}

		int best = 0;

		for (int[] beacon : beacons) {
			int depth = 0;

			while (depth < 4) {
				String below = byPosition.get(key(beacon[0], beacon[1] - depth - 1, beacon[2]));

				if (!pyramidBlock.equals(below)) {
					break;
				}

				depth++;
			}

			best = Math.max(best, depth);

			if (best == 4) {
				break;
			}
		}

		return Math.max(1, best);
	}

	private static String mostCommon(Map<String, Integer> counts) {
		String best = null;
		int bestCount = 0;

		for (Map.Entry<String, Integer> entry : counts.entrySet()) {
			if (PerimeterPlan.BEACON_BLOCK.equals(entry.getKey())) {
				continue;
			}

			if (entry.getValue() > bestCount) {
				best = entry.getKey();
				bestCount = entry.getValue();
			}
		}

		return best;
	}

	private static CompoundTag vec3(int x, int y, int z) {
		CompoundTag tag = new CompoundTag();
		tag.putInt("x", x);
		tag.putInt("y", y);
		tag.putInt("z", z);
		return tag;
	}

	private static ListTag paletteTag(List<String> palette) {
		ListTag list = new ListTag();

		for (String block : palette) {
			CompoundTag entry = new CompoundTag();
			entry.putString("Name", block);
			list.add(entry);
		}

		return list;
	}

	private static long key(int x, int y, int z) {
		return ((long) (x & 0x3FFFFFF) << 38) | ((long) (z & 0x3FFFFFF) << 12) | (y & 0xFFF);
	}
}
